process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin.on('data',function(chunk){
    process.stdin.write('data-->');
    process.stdout.write(chunk);
});
process.stdin.on('end',function(){
    process.stderr.write('End!');
});